var questions = [ 'Do you squeeze the toothpaste tube or roll it? What’s the advantage of your method?',
  'How many siblings do you have? What’s your birth order?',
  'What’s something you’ve won and how did you win it?',
  'What’s one of your nicknames? What do you prefer to be called?',
  'What’s something your parents used to say to you as a child that you promised yourself you’d never say—but now you catch yourself saying all the time?',
  'What’s something you intended to do today, but didn’t? Why not?',
  'Using only one word per person, what was your first impression of each person present with you now?',
  'What’s something that people do in traffic that really bothers you?',
  'Who is the closest friend you’ve ever had? Describe that relationship.',
  'What books on your shelf are begging to be read?',
  'What room in your house best reflects your personality? Explain why.',
  'How often do you doodle? What do your doodles usually look like?',
  'What do you do if you can’t sleep at night? Do you count sheep, toss and turn, or get up and try to do something productive?',
  'Which do you do more often: hum or whistle? Hum or whistle your answer.',
  'What animal are you the most like? Why?',
  'How many days could you last in solitary confinement? How would you do it?',
  'Do you save old greeting cards and letters, or throw them all away? Why?',
  'On a scale of one to ten, how well do you sing?',
  'When you’re alone at home, do you wear shoes, socks, slippers, or go barefoot?',
  'What are the advantages and disadvantages of being your height?',
  'When was the last picnic you went on? Describe it.',
  'How many discount or savings coupons do you clip in an average month? How many expire before you use them?',
  'Who’s the biggest “pack rat” you know?',
  'Whose autographs have you collected?',
  'What’s something you should throw away, but can’t? Explain.',
  'What food items did you eat so far today?',
  'How often do you get a haircut? Describe your worst haircut.',
  'How particular are you about the maintenance of your car?',
  'Who’s the most famous person you have ever met? What famous person would you most like to meet?',
  'What is your most unusual nighttime or morning ritual?',
  'How often do you read your horoscope? Do you believe there’s any truth to it?',
  'What kinds of movies do you most enjoy? Why?',
  'When was the last time you stubbed your toe so hard it brought tears to your eyes?',
  'How do you get rid of pesky phone calls from telemarketers?',
  'What are you a “natural” at doing?',
  'What’s the story behind a time when you got locked out?',
  'When’s the last time you had to give a speech? How did it go?',
  'How often do you get sick?',
  'What’s something valuable that you accidentally dropped and broke? Describe the situation.',
  'What’s the first thing that comes to mind when you hear the word “fun”?',
  'At amusement parks, are you drawn more to the scariest roller coaster or the tamest merrygo-round? Why?',
  'When’s the last time you square-danced or line-danced? Rate your dancing ability on a scale of one to ten.',
  'What are some of the wildest animals you’ve ever touched?',
  'How many hours do you spend on your computer each day? How much time do you spend “surfing the Web”?',
  'What makes you tick?',
  'What has been your best work of art? Describe it.',
  'What is something mischievous you have done?',
  'When you leave a room, do you turn the lights off behind you or keep the lights on throughout your house most of the time? Explain your answer.',
  'What’s the worst tasting thing you’ve ever eaten?',
  'When talking to someone while standing, are your arms usually at your sides, in your pockets, crossed in front of you, or gesturing descriptively? Demonstrate your answer.',
  'What magazines do you subscribe to, and how many of those do you actually read or look through? Do you throw any of them away unread?',
  'Have you ever purchased anything from a telemarketer? If so, what was it? If not, why didn’t you?',
  'How frequently do you purchase lottery tickets or mail in sweepstakes registrations? Have you ever won anything from them?',
  'What’s the best New Year’s resolution you’ve ever made?',
  'When making an entrance into a social gathering, do you make your presence known so everyone notices you, slip in and look for someone you know, or sneak in as quietly as possible and find a safe spot to hide? Why?',
  'How many hours a week do you watch TV? Is that too little, too much, or just enough?',
  'What’s your favorite kind of candy?',
  'What’s your strongest sense?',
  'Are you most likely to finish your taxes as soon as you receive your W–',
  'or as close to April',
  'as possible? How many times have you filed for an extension?',
  'What can your friends predict you will grumble about most?',
  'Do you prefer keeping the television channel remote in hand or giving it up? Why?',
  'How many times a day do you look at yourself in the mirror?',
  'When you travel, do you pack too much or too little? Explain.',
  'What’s the wackiest belief you held as a child?',
  'What’s your favorite beverage?',
  'What are the best steps you’ve ever taken in an effort to improve your health?',
  'When relaxing on the floor, do you sit crosslegged, fold your legs to one side, sit with your legs straight out in front of you, or recline?',
  'Have you ever been an audience member for any television shows? Which ones? For which ones would you like to be an audience member?',
  'What’s one fashion trend you hope never comes back? Which ones have come back that you wish hadn’t?',
  'What magic tricks do you know? Perform one now.',
  'What’s the best (or funniest) commercial you’ve ever seen?',
  'When was the last time you sat on a park bench for more than ten minutes? Describe the occasion.',
  'What’s the most embarrassing thing you’ve seen someone else do?',
  'When something is funny, do you usually laugh raucously, hiss, snort, chuckle quietly to yourself, or smile and nudge the person next to you?',
  'How important is it to you that people remember, spell, and pronounce your name correctly? Why?',
  'What’s your favorite item to cook? Why?',
  'Do you usually send serious or humorous greeting cards? Why?',
  'Would you ever be interested in observing a surgery or do you turn away when the nurse brings out the needle? Why?',
  'Which movies have you watched over and over again?',
  'What do you admire most about your best friend?',
  'What was one vacation that lasted too long?',
  'To feel rested, how many hours of sleep do you need each night?',
  'What’s one guilty pleasure you enjoy too much to give up?',
  'Who performs more random acts of kindness than anyone else you know? Give the details.',
  'What jingle comes to your mind? Hum or whistle it right now and see if others can correctly guess it!',
  'How many credit cards do you have? How often do you use them?',
  'How often do you leisurely eat a meal with friends?',
  'Who’s the jolliest person you know? Describe him or her.',
  'What sound drives you crazy?',
  'What sound lulls you to sleep?',
  'Who’s the smartest person you know?',
  'What food do you eat for comfort?',
  'How often do you read the newspaper? Which sections do you turn to first?',
  'In one sentence, how would you describe your best friend?',
  'How long, on average, does it take you to fall asleep once you turn out the lights?',
  'What items do you currently have stored in the trunk of your car?',
  'Which animals scare you most? Why?',
  'What remedy for curing the common cold works best for you?',
  'Where are you ticklish? How much does it bother you to be tickled?',
  'Is the paper money in your possession right now organized sequentially according to denomination and with the bills right side up and facing the same way? Why or why not?',
  'Are you a hugger or a non-hugger? Why?',
  'What drives you crazy?',
  'Are you serious-minded or a jokester? Why?',
  'Are you more likely to avoid conflict or engage in it head-on? Why?',
  'What was the most recent compliment you received and savored?',
  'What’s something about yourself that you hope will change, but that probably never will?',
  'What’s something about yourself that you hope will never change?',
  'Are you a leader or a follower? How do you know?',
  'Are you more of a rule breaker or a rule keeper? Why?',
  'Would you describe yourself as an extrovert or an introvert? Give an example.',
  'Would you describe yourself as more of a feeler or a thinker? Why?',
  'Are you usually late, early, or on time? Why?',
  'What goals have you recently set for yourself, and how are you doing on them so far?',
  'To what degree are you patriotic? How do you express your patriotism?',
  'Are you a creature of habit? Explain your answer.',
  'In what situations are you most likely to procrastinate?',
  'What books have made a big impact on you?',
  'At what age do you hope to retire? Explain.',
  'How much of a bargain hunter are you? Explain.',
  'How much of a shopper are you? Where’s your favorite place to shop?',
  'Are you ever a high-maintenance person? Explain.',
  'When was the last time you really pushed yourself to your physical limits? Explain.',
  'What’s one of your hobbies?',
  'How much poetry have you written in your life?',
  'How do you typically react in a sudden, extreme, pressure-filled crisis?',
  'How do you go about illuminating “blind spots” in your life?',
  'How mechanically inclined do you consider yourself? Give an example.',
  'How many different conversations can you adequately carry on at the same time?',
  'Are you a person who has a whole lot of acquaintances or just a few very close friends? Why?',
  'How comfortable are you with uncertainty? Explain.',
  'On a scale of one to ten, how computer savvy are you? Explain.',
  'Are you superstitious? Give an example.',
  'What one word best describes your mother?',
  'What one word best describes your father?',
  'Do you have a collection? If so, what do you collect and why?',
  'When are you shy?',
  'Do you tend to save everything or toss everything? Why?',
  'What’s something you regret losing, selling, or giving away? Explain why.',
  'How absentminded do you get? Give an example.',
  'Which is better: your short-term or your longterm memory?',
  'What’s your idea of cute?',
  'Are you more inclined to “build your own empire” or “unleash the potential of others”? Explain.',
  'What do you take for granted the most?',
  'How often do you interrupt others while they are talking? Give a reason for your answer.',
  'When you have nothing pressing, where does your mind drift?',
  'What are your career goals?',
  'How competitive are you? Explain.',
  'Are you a penny-pincher or a big spender? Why?',
  'Would you describe yourself as more laid back or more intense? Why?',
  'Are you a risk taker? Why or why not?',
  'Do you care more about pleasing people or speaking the truth? Explain your answer.',
  'What inspires you to write?',
  'What big challenge have you taken on recently?',
  'When was the last time you wanted to scream? Explain.',
  'Do you ever double or triple check things? If so, what?',
  'What bores you?',
  'What’s someone’s idiosyncrasy that really bothers you?',
  'What’s an idiosyncrasy or strange habit that you have?',
  'On a scale of one to ten, how controlling a person are you? Explain.',
  'What bad habit do you wish you could break?',
  'On a scale of one to ten, how much of a perfectionist are you? Explain.',
  'What’s a strange occurrence you’ve observed but, until now, have never (or rarely) shared with anyone?',
  'Where do you think you spend most of your money?',
  'What do you think about more than anything else?',
  'What books are you reading these days?',
  'What allergies do you have?',
  'How tolerant a person are you?',
  'To what extent do others’ beliefs influence you? Why?',
  'To what degree do you consider yourself athletic? At which sports do you excel?',
  'What causes you to get flustered?',
  'At what time of the day do you feel your best?',
  'What time do you usually wake up in the morning? Do you awaken naturally or need an alarm?',
  'What fear would you like to overcome?',
  'When do you most feel like a slave to time?',
  'What do you consider your best quality?',
  'Are you more task oriented or people oriented? Why?',
  'How do you feel about your age?',
  'Is it more important to you to look good or feel good? Explain.',
  'What’s your idea of a good time?',
  'Are you a compulsive shopper or do you bring a list and carefully consider your purchases? Why?',
  'Who is the first person you tell when something good happens to you?',
  'Whom do you run to when something bad happens in your life?',
  'In what circumstances do your motor skills short-circuit your verbal skills, and vice versa?',
  'In what situations are you most uncomfortable?',
  'When are you the most at ease with yourself?',
  'How good are you at multitasking? Give an example.',
  'What do you do when you want to relax?',
  'Are you an early bird or a night owl? Why?',
  'What’s something that amazes you?',
  'Do you say “goodbye” quickly, slowly, or not at all? Why?',
  'What spells adventure for you?',
  'What tests the limits of your sense of balance?',
  'How much of a “people watcher” are you? In what places do you find yourself “people watching”?',
  'What do you like and dislike most about your current job?',
  'Whom do you call when you need a hand?',
  'What is your greatest physical challenge?',
  'Under what circumstances is it impossible for you to sleep?',
  'How do you best avoid conflict?',
  'How accident-prone are you? Describe a recent incident.',
  'What’s the most important thing about you?',
  'What’s your favorite ice-cream brand and flavor?',
  'What’s your all-time favorite meal, and how often do you enjoy it?',
  'What’s your all-time favorite movie, and how many times have you seen it?',
  'What’s your dream job?',
  'When you need to confront someone, would you rather communicate in person, on the phone, by e-mail, or by letter? Why?',
  'Which do you prefer: the hustle and bustle of city life or the quiet and serenity of country life? Why?',
  'Do you read or study best in silence or in a place with background noise? Why?',
  'Do you prefer exercising your mind or your body? How frequently do you do either?',
  'Do you prefer that people shoot straight with you or carefully temper their words? Why?',
  'Are you more of a dog person or a cat person? Why?',
  'What’s your preference: plane, train, boat, automobile, horse, or camel?',
  'How far in advance do you prefer to plan? Why?',
  'What’s your favorite board game? Do you usually win?',
  'Who’s your favorite talk show host?',
  'Are you a traveler or a homebody? Explain.',
  'Do you enjoy a good debate or prefer keeping the peace?',
  'What was your favorite recess activity: Dodgeball, Kickball, Four Square, Hopscotch, Freeze Tag, or jump rope?',
  'What’s your favorite room in your home? Why?',
  'Where’s your perfect dream vacation spot?',
  'Where’s your favorite place to take out-of-town guests?',
  'Do you prefer to thoroughly deliberate options or decisively draw conclusions? Why?',
  'What is your favorite style of music, and how often do you listen to it?',
  'What’s your pick: hang glide, sky dive, bungee jump, hot air balloon, or kite?',
  'Which of the five senses do you treasure most? Why?',
  'When you find yourself in an argument, do you prefer to leave and resolve it later or stay and settle it right away? Why?',
  'What’s one thing you would rather pay someone to do than do yourself? Why?',
  'What’s one book you recommend and why?',
  'What annoys you most about women?',
  'What annoys you most about men?',
  'What do you like most about women?',
  'What do you like most about men?',
  'What’s your favorite genre of literature?',
  'What’s your preferred method of getting the news?',
  'What’s your favorite color? Why?',
  'What’s your favorite question to ask? What’s your favorite question to answer?',
  'What’s your favorite expression?',
  'What’s your all-time favorite video game?',
  'What real person, dead or alive, do you wish you could be more like? Why?',
  'What’s your all-time favorite band, and what would you give to meet them?',
  'What’s your least favorite thing to do? Why?',
  'What’s your favorite subject to discuss? Why?',
  'When you fly, do you prefer to arrive at the airport extra early or get there just in the nick of time? Why?',
  'Whom do you most admire? Why?',
  'What bothers you most about perfectionists?',
  'How do you prefer to give constructive criticism? Do you typically wait for someone to ask for it or not? Why?',
  'What are your three favorite television shows? How frequently do you watch them?',
  'Of all the tools and gadgets you own, which one do you most enjoy using?',
  'What is one of your favorite souvenirs brought back from your travels? Where do you keep it?',
  'What’s your choice: baseball, football, Frisbee, Hacky Sack, or boomerang?',
  'What are the best and worst sounds in the world?',
  'When you go to a movie, do you like to sit in the back, middle, or front? Why?',
  'Where’s your favorite spot from which to view the sunrise or sunset?',
  'What’s your most and least preferred forms of exercise? Explain.',
  'Growing up, what was your favorite fairy tale or children’s story? Why?',
  'What’s your choice: jigsaw, crossword, or numeric puzzles?',
  'What is your favorite bumper sticker or t-shirt slogan?',
  'What’s your favorite aroma or fragrance?',
  'What’s your favorite spectator sport, and how often do you watch it?',
  'What’s one of your favorite summer activities to do with family or friends?',
  'Do you prefer to plan your vacation or be spontaneous? Why?',
  'What’s your pleasure: horseshoes, shuffleboard, croquet, archery, or darts?',
  'What are your favorite summer and winter sports?',
  'What’s your most treasured piece of jewelry? Why?',
  'What’s your reaction toward people who are outspoken about their beliefs? What conditions cause you to dislike or, conversely, enjoy talking with them?',
  'What is something that bothers you if it is not done perfectly? Why is that so?',
  'Who is your favorite musician, and how often have you seen him or her perform?',
  'Who’s your favorite comedian?',
  'What’s your fancy: bird watching, butterfly collecting, flower hunting, shell gathering, or star gazing?',
  'What’s your favorite fast-food restaurant and how often do you go there?',
  'What’s the name of your favorite magazine? What do you like most about it?',
  'What’s the worst movie you’ve ever seen, and who did you see it with?',
  'When driving, are you more likely to listen to the radio, to CDs and tapes, or nothing at all? Why?',
  'What’s your fancy: skateboard, roller blades, roller skates, ice skates, or snowboard?',
  'What’s your preferred way to meet new people? Explain.',
  'Where’s your favorite place to be? Why?',
  'How do you prefer to learn or memorize new information?',
  'What’s your pleasure: tennis, badminton, volleyball, racquetball, or Ping-Pong?',
  'What is your favorite day of the week? Why?',
  'What’s your favorite season of the year? Why?',
  'When you are home alone, do you need the stereo, radio, or TV turned on? Or do you prefer the quiet? Explain.',
  'What’s your preference: wrestling, martial arts, boxing, or fencing?',
  'Do you have a set place for everything at home or do you simply let things stay wherever they land? Give some examples.',
  'Who’s the best cook you know, and what’s his or her specialty?',
  'Who’s the most creative or artistic person you know?',
  'What’s your preference: motorcycle, dirt bike, moped, mountain bike, racing bike, scooter, or unicycle?',
  'What is your favorite poem or saying? Why is it your favorite?',
  'What’s your favorite quote? Why is it special to you?',
  'Do you prefer window or aisle?',
  'As you fall asleep, do you prefer to be flat on your back, curled on your side, or on your stomach? What position are you in when you wake up?',
  'What type of museum do you most like to visit?',
  'What strikes your fancy: zoo, circus, carnival, county fair, or parade?',
  'What’s your preference: cruise ship, powerboat, sailboat, rowboat, kayak, or inner tube?',
  'What’s your favorite holiday tradition? What meaning does it have for you?',
  'Where’s your favorite place to go when you want to be alone? Why?',
  'Do you remember jokes very well? What’s the best joke you’ve heard recently?',
  'Who’s your favorite person in the whole wide world? Why?',
  'What’s your all-time favorite town or city? Why?',
  'Do you have a favorite painting or drawing? What makes it special to you?',
  'What social issue fires you up?',
  'What are the top three qualities that first draw you to someone new?',
  'What’s one of your greatest achievements?',
  'What’s your favorite birthday memory?',
  'Who was your best friend in high school, and where is he or she now?',
  'What was your first job? How much did you get paid?',
  'As a kid, what did you want to grow up to be?',
  'What photos do you cherish from the past? Where do you keep them now?',
  'Was there ever a time when it turned out you were right, in spite of many others who thought otherwise? Explain the situation.',
  'What one word sums up your high school experience?',
  'When was the last time you played hooky? Explain the situation.',
  'As a child, what was your idea of fun?',
  'When have you experienced poor customer service? How did you react?',
  'What do you remember about your first day of school or your first teacher?',
  'What’s your most memorable (good or bad) airplane flight?',
  'How many bones have you broken? Share the details.',
  'What’s something you’ve done that surprised even you?',
  'How many times have you had stitches, and what were the circumstances? Explain.',
  'What pets did you have growing up? What were their names?',
  'Have you ever seen or called a psychic? What was your experience like?',
  'Was school easy or difficult for you? How s',
  'What kind of kids did you hang out with in high school?',
  'Who was your favorite teacher growing up, and what did you like most about him or her?',
  'What is the best bargain you ever found?',
  'What’s your most treasured heirloom?',
  'Can you remember the address of one of your childhood homes? If so, what was it?',
  'How have your priorities changed over time? Explain.',
  'When did you get your first traffic ticket? Share the details.',
  'What’s the most dangerous situation you’ve encountered? How did you react?',
  'How did someone plan a surprise for you? What was your reaction?',
  'What was your favorite subject in school? Why?',
  'Who has made the biggest impact on you? Explain.',
  'Who has been your friend the longest? How and when did you meet him or her?',
  'Did you or someone you know ever talk a police officer out of writing a ticket? Describe the situation.',
  'Growing up, for which holidays did your family decorate the house?',
  'Have you ever helped a total stranger? If so, how?',
  'Growing up, what was your favorite comic strip?',
  'What was an act of kindness you offered or received?',
  'Have you dreamed of flying, falling, or running? Describe your most vivid memory of one of these dreams.',
  'Have you ever had a premonition that actually came true? Explain.',
  'Have you ever served on jury duty? If so, what was the case about? If not, would you like to be on a jury in the future?',
  'Did a sibling or childhood peer ever tease or torment you? Share the details.',
  'What childhood accident stands out in your mind?',
  'When the “tooth fairy” came, what did you usually get?',
  'What’s your favorite picnic memory?',
  'Who was your least favorite teacher? Why?',
  'Have you ever been let off the hook for a punishment you deserved? How did that make you feel?',
  'Did you ever cheat on a school exam? Describe the situation.',
  'What was a childhood disillusionment you experienced?',
  'As a child, did you take music lessons or take part in band or choir? Explain.',
  'What “close call” did you have from the past? Describe it.',
  'What’s the best advice you’ve ever been given?',
  'How much trouble did you get into during your school days? Explain.',
  'As a child, did you ever peek into a wrapped gift before you actually received it? Did you ever get caught? Explain the details.',
  'What dream has come true for you?',
  'What’s one of the biggest purchases you made, and how did you negotiate the transaction?',
  'What is your earliest childhood memory?',
  'What nightmare woke you up in a panic?',
  'How has your birth order affected you?',
  'Have you ever suggested an idea for change that was adopted? What was it?',
  'What’s the best prank you’ve ever pulled off?',
  'What’s the best prank someone pulled on you?',
  'Growing up, for the most part, were you respectful or disrespectful to your parents? Explain.',
  'What lasting lesson did you learn from your parents?',
  'What was the last concert you attended? Who did you go with?',
  'What one new thing did you learn in the last week?',
  'How many foreign countries have you visited? Which one stands out in your memory?',
  'How many American states have you visited in your lifetime? Which was your favorite and why?',
  'What has frustrated you in the recent past? Explain.',
  'In what sports, clubs, or activities were you most involved during high school?',
  'Who was your first boyfriend or girlfriend? What was he or she like?',
  'What is the first movie you saw in a theater?',
  'What was the name of your first album/CD?',
  'What’s something that you did growing up that your parents never found out about?',
  'When were you in a situation where something struck you as funny, but it was inappropriate to laugh? What did you do to suppress your laughter? Explain the situation.',
  'What’s a favorite memory with your grandparents?',
  '“Life is not measured by the number of breaths you take, but by the moments that take your breath away” (George Carlin). When have you had such a moment?',
  'When were you in a hospital? Describe the situation.',
  'Have you (or someone you know) ever been on national television? Describe the situation.',
  'Have you ever participated in a long distance walking, running, or biking event? Tell your story.',
  'How many times did you move growing up? Describe your experience and how it impacted you.',
  'What’s the worst weather situation you’ve been in? Explain.',
  'How would you describe your most magical childhood moment?',
  'How would you summarize the highs and lows of this past week?',
  'What was your best or worst job interview?',
  'Have you ever had a challenging roommate situation? What was difficult about it?',
  'What was your worst “nightmare” date?',
  'What was your most romantic date?',
  'What event in your life has brought about the greatest life-change?',
  'What was one of your most frightening moments?',
  'Was there ever a time when you or someone you know was a victim of fraud? Explain.',
  'What was the best or worst job you ever had?',
  'What outside influences have had the greatest impact on your family?',
  'What’s the best thing you ever built or created?',
  'What’s the story behind a time when a car you were in broke down?',
  'What’s the most adventurous or daring thing you have ever done?',
  'What are your best or worst childhood memories of going to a zoo or circus?',
  'What was a recent déjà vu experience?',
  'Did you ever learn to swim? If so, how did you learn? Describe your experience.',
  'How would you describe one of your happiest childhood memories?',
  'What lesson did you have to learn the hard way?',
  'When did you last have fresh flowers in your home? What was the occasion?',
  'If you could be invisible for a day, what would you do?',
  'If you could eliminate one weakness or limitation in your life, what would it be?',
  'If you could change anything about your relationship with your parents, what would it be?',
  'If you could switch job responsibilities with your boss, would you do it? Why or why not?',
  'If you were able to retrieve only one item on the way out of your burning home, what would that be? Explain.',
  'If you could go back in time, what year would you visit? Why?',
  'If you could go anywhere for a one-day visit, where would you go? Why?',
  'If you could spend one hour doing absolutely anything, what would you do?',
  'If you had the opportunity to travel into space, would you go? Why or why not?',
  'If you had an unlimited shopping spree at only one store, which one would you choose? Why?',
  'If you could play any instrument, what would you choose? Why?',
  'If you could talk with only one person for the rest of your life, who would it be and why?',
  'If you could visit with any person in history, who would it be and why?',
  'If you could do something very daring without fear, what would you do?',
  'If you could take an early retirement, what would you do?',
  'If you had the chance to go anywhere for dinner tomorrow, where would you go? Why?',
  'If you were assured you would not fail, what endeavor would you attempt?',
  'If you could be any celebrity, who would you want to become? Why?',
  'If you won a million dollars in the lottery, how would you spend it?',
  'If you had to perform a “Stupid Human Trick” for the David Letterman show, what would you do?',
  'If you could learn to speak a foreign language, which one would you choose and why?',
  'If you could change one thing about your appearance, what would it be?',
  'If you could change one thing about your personality, how would you be different?',
  'If you were stranded on a deserted island, what three “luxury items” would you most want to have with you?',
  'If you could rule the world for one day, what would you do?',
  'If you could change your occupation, what would you do?',
  'If you could give one gift to your children, what would it be?',
  'If you could live anywhere in the world, where would it be?',
  'If you were able to listen to only one music CD ever again, what would it be and why?',
  'If you were to write a book about your life, what would it be called?',
  'If you were imprisoned and were allowed only one book to read, what would you choose and why?',
  'If you could restore one broken relationship, which one would you choose? Why?',
  'If you could bring one person back from the dead, who would you bring back? Why?',
  'If you could live your life all over again, would you? Explain.',
  'If you could possess it, what superhero’s super power would you want to have and why?',
  'If you had to change your first name, what name would you choose?',
  'If you had the opportunity to start your own business, what would you start? Why?',
  'If you could cure a disease or heal a sickness, which one would you choose? Why?',
  'If you could bring peace to one country, which one would you select? Why?',
  'If you could look into the future to find out one thing, what would you want to know?',
  'If you could relive any year, what year would you choose? Why?',
  'If you could have invented one thing, what would it have been?',
  'If you could develop something that’s not been invented yet, what would you invent?',
  'If you were a WWE Smackdown champion wrestler, what would be your name and calling card?',
  'If there were no animals in our world, what would we be missing?',
  'If you were a master sculptor for a day, what would you sculpt?',
  'If you were offered free cosmetic surgery by the best plastic surgeons in the world, would you take it? Explain.',
  'If you could rob from the rich and give to the poor and get away with it, would you do it? Why?',
  'If you could rid the world of one evil, which one would it be? Why?',
  'If you were stranded on a deserted island, which three people would you most want to have join you?',
  'If you could own any sports team, which one would it be?',
  'If you had the ability to compete in the Olympics, what event would you want to be in?',
  'If you had the talent to play a professional sport, which one would you select?',
  'If you could establish one charitable organization, what would it be?',
  'If you could turn into any animal at will, which one would you select? Why?',
  'If you could read everyone’s mind for one week only, would you tell anyone or keep it a secret? Explain.',
  'If you could be a radio or television personality, what kind of program would you choose?',
  'If you were in charge of ending world hunger, where would you start?',
  'If you had the time to volunteer for any worthwhile organization, which one would you choose? Why?',
  'If you had to design a float for a parade, what would you design?',
  'If you could live forever on earth, would you choose to do so? Explain.',
  'If you were to paint a picture of your childhood, what colors would you use? Describe your picture.',
  'If you were on a debate team, what subject would you relish debating?',
  'If you could rid the world of one fear, what fear would it be? Why?',
  'If you could write a best-selling book, what would you write about?',
  'If you were a doctor, which field of medicine would you specialize in? Why?',
  'If you could change one thing about the culture you live in, what would it be? Why?',
  'If you were required to distribute a million dollars any way you wanted, how would you do it?',
  'If you were to star in a movie, what would be your ideal role?',
  'If you could rewrite history, what one thing would you change?',
  'If you were forced to give up one of your five senses, which one would you choose? Why?',
  'If you had to choose right now, who would you select to be in your wedding party?',
  'If you were a gifted painter, what picture would you want to paint first?',
  'If you could give some advice to all parents, what would you say?',
  'If you had to do your life over, what one thing would you do differently? Explain.',
  'If you could be any cartoon character, which one would you be?',
  'If you could make any improvement on how cars operate, what would it be?',
  'If you could teach any class on any subject, what would you teach and to whom would you teach it?',
  'If you could wave a magic wand and stop any one thing, what would you stop? Why?',
  'If you could ask any question of the people you’re with right now and get an honest answer, what question would you ask?',
  'If you could trade places with anyone for one week, who would you want to trade with and why?',
  'If you could make one character from any work of fiction come to life, what character would you select?',
  'If you were a great explorer, what would you explore?',
  'If you could be a contestant on any game show, which one would it be?',
  'If you found an abandoned car with $50 in the back seat, what would you do?',
  'If you could own a restaurant, what kind would it be?',
  'If you could run Hollywood, what would you do?',
  'If you could transport yourself at will between any two destinations, which two would you choose? Why?',
  'If you could redecorate your home at no cost, what would you wish to do?',
  'If you could be any age for the rest of your life, what age would you choose? Why?',
  'If you could capture any event in history on videotape, which one event would it be?',
  'If you were to get a tattoo, what would it be? And where would you put it?',
  'If you could grant any three wishes to one person, to whom would you grant them? Why?',
  'If you were going to a costume party next week, what costume would you wear?',
  'If you could take back something you’ve said, what would it be?',
  'If you were to fast-forward your life five years, where would you be and what would you be doing? What changes would people see in you?',
  'If you could say anything to the people you’re with right now, what would you say?',
  'If you were given $100 to celebrate someone or something, who or what would you celebrate?',
  'If you could give one piece of advice to pass on to the next generation, what would it be?',
  'If you could hang a motto in every home, what would it say?',
  'What does “success” mean to you?',
  'Do you think there will ever be world peace? Why or why not?',
  'What’s the secret to a long life?',
  'Which is the greater tragedy: an innocent person imprisoned or a guilty person set free? Explain.',
  'How important is it to set personal goals?',
  'Are people trustworthy? Explain your answer.',
  'What is beauty?',
  'Why do you think people live in denial?',
  'What new law is needed to make the world a better place to live?',
  'How would you describe the perfect day?',
  'In your opinion, what is the moral condition of this world?',
  'Why do you think divorce is so prevalent?',
  'What is the ideal age to get married? Why?',
  'To what extent is knowledge power, to what extent is truth power, and what’s the difference?',
  'Do you believe that the human soul is eternal?',
  'What is the greatest invention the world has ever seen?',
  'What do you think is needed to make the world a better place?',
  'What advice can you give about how to conquer fear?',
  'What advice can you give about how to relieve stress?',
  'Why are some people cruel and unkind?',
  'What is the difference between knowing a lot of facts about a person and knowing someone personally?',
  'What do you think is the secret to a happy marriage?',
  'Why do innocent people suffer?',
  'Why do bad things happen to good people?',
  'Do you believe that, for the most part, people are basically good, basically bad, or a mixture? Why?',
  'Is seeking truth a way of life or a season of life? Explain.',
  'Do you believe ignorance is bliss? Why or why not?',
  'Why do you think it’s so hard for people to say they’re sorry?',
  'When does the end justify the means?',
  'What do you think is the greatest problem of the human race?',
  'Why are bad habits so hard to break?',
  'Whom do you consider the greatest president of all time? Why?',
  'What is truth?',
  'What’s more important, a healthy mind or a healthy body? Why?',
  'What makes a true friendship?',
  'Does life imitate art or does art imitate life? Explain.',
  'What is “unconditional forgiveness”?',
  'To what extent is it possible to show respect or tolerance and still disagree?',
  'What does it mean when two people are said to have “chemistry”?',
  'Do you think science will offer the “final answer” to all the world’s problems? Why or why not?',
  'To what extent is cloning a moral issue? Explain.',
  'When is it better to be safe than sorry?',
  'What does it mean to be powerful?',
  'What is the benefit of meditation?',
  'Why is it sometimes hard to forgive others?',
  'What’s most intriguing about the Cinderella story?',
  'How well do you receive criticism from others? Why do most people fear honest feedback and evaluation?',
  'What does this quote mean? “He is no fool who gives what he cannot keep, to gain what he cannot lose.” (Jim Elliot)',
  'What’s the best approach for resolving conflict?',
  'Which is more important: what you say or how you say it? Explain your answer.',
  'Do you think a sixth sense exists? Explain.',
  'Do you think the end or the means is most important? Explain.',
  'When is it appropriate to resort to making a threat? When is a threat not a threat?',
  'What role does trust play in our everyday relationships?',
  'What’s the best way to earn another person’s respect?',
  'When is it necessary to take the law into your own hands?',
  'What is the basis of your standard of right and wrong?',
  'What’s the best way to win back an estranged friend?',
  'What’s the best way to resist peer pressure?',
  'Which is greater, love of one’s parents, one’s children, one’s spouse, or one’s friends? Explain your answer.',
  'What do you think is the most significant event in the history of the human race? Explain.',
  'How would you define “freedom”?',
  'What are the best ways to inspire or motivate people?',
  'What’s the best way to delegate things to others?',
  'In raising children, do you think it’s best to discipline by giving timeouts, discussions, spankings, or a combination? Why?',
  'What’s the best way to negotiate a raise in salary?',
  'Where do you draw the line between helping people and showing them how to help themselves? How do you strike that balance?',
  'What’s a sure way to detect when someone is lying?',
  'How do you measure contentment?',
  'Why do some people resist living lives of moral integrity?',
  'What’s the best way to handle another person’s hostility and ease tensions?',
  'How important is physical appearance when it comes to achieving success or getting one’s way in life?',
  'Is cloning a sign of progress? Why or why not?',
  'What’s the age of accountability?',
  'What is the secret to being content in all circumstances?',
  'Who’s the greatest leader of all time? Why?',
  'Does work really banish three great evils— boredom, vice, and poverty? Explain.',
  'What do you recommend to overcome self-pity?',
  'If you did something wrong, would it make any difference that you did so unintentionally? Would you still be morally responsible? Explain.',
  'How do you define “true love”?',
  'What’s the best approach to use in negotiating a fair purchase price for a car?',
  'How do you suggest overcoming negative self-talk?',
  'Why is it taboo to discuss personal financial matters?',
  'What’s the best remedy for anxiety caused by speaking in front of a large group of people?',
  'When is failure a success?',
  'Is there such a thing as a “just war”? Explain.',
  'What’s your position on capital punishment?',
  'What is the meaning of life?',
  'Why is life so hard? Why is life so complicated?',
  'What’s unforgivable?',
  'If accumulation of money doesn’t bring lasting happiness, what does?',
  'Why are people who win the lottery often unhappier than they were before their win?',
  'What happens after death?',
  'What is it about human nature that tends to stubbornly refuse the aid of someone else?',
  'What is the difference between an intellectual assent to a set of beliefs and an actual acceptance of those beliefs?',
  'What purpose do the emotions of regret, shame, or guilt serve?',
  'Do you think religious holidays have become too commercialized by society? Why or why not?',
  'Do you think the general population is better off or worse off than it was fifty years ago? Why?',
  'What’s the difference between intelligence and wisdom?',
  'What’s one thing you know for sure?',
  'What’s one regret you live with?',
  'What do you live in denial about?',
  'What phobias have you struggled with?',
  'How difficult is it for you to forgive someone who refuses to apologize?',
  'What’s the most serious illness or injury you ever faced?',
  'How are you different now than you were before September',
  'How would you prefer to die—quickly without warning or slowly over time?',
  'What insults your intelligence?',
  'What’s one conviction you hold that you would be willing to die for?',
  'When is it okay to lie?',
  'What’s your most embarrassing moment?',
  'When have you had to agree to disagree? Explain.',
  'What bad habit have you broken?',
  'In an emergency, which friends would you feel the freedom to call in the middle of the night?',
  'Where are you going?',
  'What impossible task are you facing right now?',
  'What fear are you trying to overcome?',
  'Would most people describe you as humble or proud? Why?',
  'Have you ever violated a confidence? Describe what happened.',
  'Have you ever been falsely accused? Describe the situation and how you felt about it.',
  'What character trait are you currently trying to improve or change?',
  'Have you ever gotten caught doing something you shouldn’t have done? Describe the occasion.',
  'Was there ever a time when you were very sure of something, but were later proved wrong? Explain what happened and how you reacted.',
  'If you just found out you had only two weeks to live, what top two or three things would you do? Why?',
  'What do you suspect people say about you behind your back?',
  'How have you been humbled? Describe the details.',
  'When was the last time you said, “It’s my fault—I’m sorry”? Explain the situation.',
  'What scares you the most about the future?',
  'What hot topic usually turns into an argument with you?',
  'In what situation do you often find yourself “walking on eggshells”?',
  'What traumatic event has changed your life forever?',
  'Who’s the “black sheep” of your family? Explain the situation.',
  'What one person in your life do you find the most challenging? Explain.',
  'What temptation have you successfully resisted? Describe the situation.',
  'What’s something about you that no one knows?',
  'How do you comfort those who have suffered a tragedy or loss?',
  'How difficult is it for you to speak the truth, even when it may be hurtful or unpopular?',
  'What was the hardest era of your life?',
  'Have you found your place in this world? If so, where is it?',
  'If you died today, who would give your eulogy, and what would be said?',
  'What one thing do you fear more than anything else?',
  'How afraid of dying are you? Explain.',
  'What’s something for which you would seek revenge?',
  'What was your last argument about?',
  'How often do you tell little white lies? Give an example.',
  'What is your greatest weakness?',
  'How do you explain death?',
  'What epitaph would you want engraved on your tombstone?',
  'What kinds of things do you catch yourself exaggerating about?',
  'What lie did you tell today?',
  'Have you ever felt like you were taking three steps forward but two steps back? Explain.',
  'What’s the closest you’ve come to having an epiphany?',
  'What would make you totally content right now?',
  'What is something that you failed at?',
  'What mystery have you solved?',
  'When you think of really living and not merely existing, what comes to mind?',
  'What’s something you consider too daring to try?',
  'How at peace are you with yourself? Explain.',
  'Would you want to know the date and cause of your death? How would that information change things for you?',
  'What is the hardest thing you’ve ever done?',
  'What do you think is your purpose in life?',
  'What’s the most ridiculous thing you’ve ever stolen? Explain the situation.',
  'What paradox (or contradiction) in life have you had to learn to accept or embrace?',
  'To what extent are you an argumentative person? Explain.',
  'Why are we here?',
  'To what extent do you trust people? Explain.',
  'Would you ever give up your life for a friend or family member? Why or why not?',
  'If you knew your death could save a stranger’s life, would you give up your life? Why or why not?',
  'What do you hope to discover beyond the grave?',
  'What lesson has failure taught you?',
  'Is your “glass” usually half full or half empty? Why?',
  'What’s the most significant loss you’ve experienced?',
  'What’s the closest you’ve ever come to thinking you didn’t deserve to live? Explain.',
  'What’s an example of your passive-aggressive side?',
  'How do you know this world is not a dream? Can you prove it?',
  'Have you forgiven yourself for past personal failures? Why or why not?',
  'In what area of your life are you immature?',
  'How do you deal with very needy people?',
  'How do you most want to be remembered?',
  'Did you ever witness someone die? Describe your thoughts and feelings at that time.',
  'What important competition have you lost?',
  'What do you hope will be your biggest lifetime contribution to society?',
  'What do you do to get “centered”?',
  'Have you ever broken or spilled something in someone else’s home? Did you try to cover it up or fix it so it would go unnoticed? Explain.',
  'How healthy or unhealthy are you with setting boundaries? Explain.',
  '“I do what I don’t want to do and I don’t do what I want to do.” To what extent do you relate to that statement? Explain.',
  'Do you ever fear “living” as much as “dying”? Explain.',
  'Was there ever a time when your blood “ran cold?” Explain.',
  'How have you dealt with loss in your life?',
  'Is there such a thing as “destiny”? Why or why not?',
  'How would you graciously turn down an invitation to go out on a date? How would you graciously break up with someone you were dating?',
  'What positives, if any, have resulted from the suffering you’ve experienced in your life?',
  'How do you deal with doubt?',
  'What holds you back?',
  'What negative behavioral pattern has been passed down from generation to generation within your family?',
  'What brings out your pessimistic side?',
  'What’s missing in your life? What one thing would make your life complete?',
  'How convinced are you that the sun will rise tomorrow? What makes you so sure?',
  'Who are you when no one’s looking?',
  'How hard is life? How does your life compare?',
  'When was the last time you cried? Why?',
  'How would you describe a time when you felt alone in a crowd?',
  'What makes you stand to your feet and cheer?',
  'On a scale from one to ten, how happy do you usually feel? Explain.',
  'What’s your most prized or sentimental possession? Explain.',
  'What or who inspires you to be all that you can be?',
  'When have you been overwhelmed with compassion or overcome with pity? How were you transformed by the experience?',
  'What in this world breaks your heart?',
  'If you had to locate the feeling of “longing” or “yearning” in your body, where would you say it was?',
  'Describe a time when you lost something very valuable. How did you feel when you finally found it or when you realized it would never be found?',
  'How do you handle anger?',
  'What stresses you out?',
  'What is something that always brings a smile to your face?',
  'What mood are you usually in? Explain why.',
  'What silly thing have you done in the name of love?',
  'When was the last time you helped someone in need? Describe it.',
  'What’s one accomplishment that gives you great satisfaction?',
  'What was your proudest moment?',
  'In relationships, are you more often the “heartbreaker” or the “heart broken”? Why?',
  'How many times have you really been in love?',
  'How many times have you had a broken heart?',
  'Whom have you lost touch with but still wonder about?',
  'How have you honored your parents?',
  'What’s the most cowardly thing you’ve ever done?',
  'Who has loved you more than anyone else in your life?',
  'What was the happiest era of your life?',
  'What’s the most courageous thing you’ve ever done?',
  'When have you recently felt overwhelmed? Describe the situation.',
  'What one thing do you wish for more than anything else?',
  'What do you dream about most often? How do you interpret your dreams?',
  'What’s the best greeting card you ever received?',
  'How have you significantly honored another person?',
  'What has recently made you depressed?',
  'Have you ever felt excluded? Explain the situation and how it made you feel.',
  'What was the best surprise you’ve ever pulled off?',
  'What was the best news you’ve ever received?',
  'When did you ever immediately “click” with someone you just met? What was the longterm result? To what do you attribute that kind of connection?',
  'Was there ever a time when you were in need and someone met that need? Describe.',
  'Is it better to have loved and lost or never to have loved at all? Explain.',
  'What prevents you from revealing your emotions to others? Give an example.',
  'What brings a tear to your eye?',
  'When do you find yourself singing?',
  'What color describes your mood right now?',
  'Is there a family tradition that has a special meaning for you? Describe it.',
  'Of the following ways, how do you most like to express your love to another person: touch, words, gifts, time spent together, or acts of kindness?',
  'Of the following ways, how do you most like to receive expressions of love: touch, words, gifts, time spent together, or acts of kindness?',
  'When do you feel the loneliest?',
  'What makes you feel like pulling the covers back over your head and staying hidden in bed all day long?',
  'What brings out your critical side?',
  'What fuels you?',
  'What poem or song really moves you? Share a line from it.',
  'What’s one thing that makes you really angry? Explain.',
  'From what do you secretly long to be “rescued”?',
  'What do you need to feel secure?',
  'What was the greatest day of your life?',
  'When you feel sad, what do you do to find comfort?',
  'What objects from your childhood have you saved? Explain why.',
  'Are you ever satisfied? Why or why not?',
  'Do you use the word “love” freely and often or selectively and seldom? Explain why.',
  'What’s weighing heavy on your heart these days?',
  'What do you do when a homeless person asks you for money? How do you feel afterward?',
  'When you are happy, how do you like to celebrate?',
  'How self-centered are you?',
  'When have you had a cathartic experience and what was the impetus?',
  'Is it better to love or be loved? Why?',
  'Do you believe in “love at first sight”? Why or why not?',
  'Do you believe in “soul mates”? Why or why not?',
  'How is your love for your friends different from your love for your family?',
  'What recent disappointment have you had?',
  'When is the right time to demonstrate “tough love”?',
  'Is there someone in your life who has never (or rarely) let you down? How long have you known this person?',
  'When do you feel insecure?',
  'To what extent do you trust your own judgment or gut instincts? Why?',
  'What worries you?',
  'How do you heal a broken heart?',
  'Who have you loved more than anyone else in your life? Explain.',
  'What do you want?',
  'When was the last time your heart skipped a beat? Describe the situation.',
  'When have you felt like you could “never repay” someone? Explain.',
  'What does silence feel like to you?',
  'What makes you feel jealous?',
  'When was the last time your heart was in your throat? Describe the situation.',
  'Was there ever a time when someone rescued you? Describe the closest thing that comes to mind.',
  'Was there ever a time when you gave your heart completely over to something or someone? Describe the closest thing that comes to mind.',
  'How often do you second-guess yourself? Why?',
  'What situations cause you to hold back and protect your heart?',
  'Have you ever felt like there was no escape; that your heart was trapped? Describe.',
  'When have you felt betrayed?',
  'What’s your most cherished romantic moment?',
  'What fills your heart up to the bursting level?',
  'When do you feel out of control?',
  'Has your heart ever lied to you, or do you think it always “tells” the truth? Explain.',
  'When was a time when you felt honored? Describe the situation.',
  'How often or easily do movies make you cry?',
  'What’s one question you are asking yourself these days?',
  'Growing up, what virtue did you see in your parents that you hope to emulate?',
  'How sensitive a person are you? Explain.',
  'What part of your heart has never been seen by anyone? Why?',
  'Have you ever had someone do something for you or give something to you that you did not earn or deserve? Describe the situation and how it made you feel.',
  'What makes your heart beat fast?',
  'Why do you think there are so many different religions in the world?',
  'Do you think that all the major religions are fundamentally the same or different? Explain your answer.',
  'Do you think religion is an emotional crutch for some people? Why or why not?',
  'What do you think heaven is like?',
  'What do you think most people think about the Bible?',
  'What do you think are the most common misconceptions people have about God?',
  'Do you believe the Bible is actually God’s chosen tool for communication to mankind? Why or why not?',
  'Do you believe in reincarnation? Why or why not?',
  'What do you like most about church, synagogue, or mosque?',
  'Why does God seem so distant?',
  'Do you think most people are spiritually attuned or spiritually ignorant?',
  'What is your attitude toward people who believe differently than you?',
  'Do you think God exists? Why or why not?',
  'If God did not exist, what practical difference would that make in our world?',
  'Is God dead? Explain.',
  'Why do you think some people are skeptical about the existence of God? Why are others so certain he does exist?',
  'Is belief in God intellectual suicide? Why or why not?',
  'Do you think it’s possible for anyone to know for sure if there is a God? Explain.',
  'Why do you think that some form of religious belief is present in virtually every culture?',
  'What do you like least about religion?',
  'Do you think religion is necessary? Why or why not?',
  'What are some characteristics you have heard taught about God that you do not believe?',
  'Do you think religion should be a private matter? Why or why not?',
  'Do you believe in miracles? Why or why not?',
  'Do you believe God is actively involved in our world or detached and distant from our world? Explain.',
  'How reliable do you think the Bible is as a historical document? Explain.',
  'How would you explain eternity?',
  'How many different religions have you studied in your lifetime, and which one makes the most sense to you right now? Explain.',
  'Do you believe in an afterlife? Why or why not?',
  'How do you think the afterlife will be different from this life?',
  'How do you “remember your spirit”?',
  'What does “being spiritual” mean to you?',
  'Do you think most, if not all, wars would cease if no religious differences existed? Why or why not?',
  'Are natural disasters God’s doing? Explain.',
  'How often do most people you know think about spiritual issues? Explain your answer.',
  'If God decided to visit the planet right now, what do you think he would say or do?',
  'Why do you think there are so many disagreements over spiritual and religious matters?',
  'How do you picture the face of God?',
  'Is your image of God more like that of a “grandfather,” a “policeman,” or a “mechanic”? Explain.',
  'What’s the central difference between psychology and religion, or do they address the same need in mankind? Explain.',
  'What about God do you hope is true? Why?',
  'What’s the difference between being moral and being spiritual?',
  'Do you think that scientific discoveries will eventually eliminate mankind’s “need” for God? Why or why not?',
  'What’s the greatest spiritual advice you have ever received?',
  'Given the pros and cons associated with deeply held religious beliefs, do you think that “religion” overall is a positive or a negative thing?',
  'Do you believe that a spiritual realm exists outside of what can be perceived by the five senses? Why or why not?',
  'How would you define “faith”?',
  'Should faith in God be “blind” or should it require evidence? Explain.',
  'What does it mean to take a “leap of faith”? Have you ever taken one?',
  'Do you believe it is possible to encounter God in a personal way? Why or why not?',
  'What, if anything, is the Bible good for?',
  'What determines how much trust you will place in a spiritual authority?',
  'Do you think a person, in order to be a certain religion, must be converted into that religion, born into it, or both?',
  'How much influence has your family heritage had on your ultimate religious beliefs? Explain.',
  'What is it that bothers you the most about religious fanatics?',
  'What are the positives and negatives of joining a small group to discuss spiritual issues?',
  'What did you like and dislike about any church services you’ve experienced?',
  'Why did God start it all?',
  'If you could design your own church service, what would it look like?',
  'How many different paths do you think there are to God? Explain.',
  'What is the difference between “faith” and “religion”?',
  'Why does merely talking about Christianity often muster up negative images and angry reactions?',
  'Generally speaking, does Christianity, with its apparent emphasis on sin, hell, and judgment, dwell too much on the negative? Explain your answer.',
  'What are the various ways people attempt to earn God’s forgiveness or favor?',
  'What is one thing you no longer believe about God that you believed when you were younger? What changed your mind?',
  'What’s one benefit the world has gained as a result of Jesus Christ’s life and teaching ministry?',
  'What’s one benefit the world has gained as a result of Muhammad’s life and teaching ministry?',
  'What’s one benefit the world has gained as a result of Buddha’s life and teaching ministry?',
  'What’s your basis for deciding which, if any, religion is right for you?',
  'Do you believe there is anything to the “power of prayer”? Explain.',
  'From where does evil come?',
  'Why is there so much evil in the world?',
  'What do you think are some methods God uses to communicate to people?',
  'Do you believe it’s possible for people to communicate with the dead?',
  'Do you believe an evil spiritual being, such as the Devil, exists? Why or why not?',
  'What is it about the Bible that most confuses you?',
  'What is your position concerning the concept of hell?',
  'If God can do anything, can he make a rock so heavy he cannot lift it? Explain.',
  'How good do you have to be to get into heaven?',
  'Can a person know for sure that he or she is going to heaven? Why or why not?',
  'Do you think all religions lead to God? Why or why not?',
  'What’s the difference between tolerance of all religions and validation of all religions?',
  'Do you think that in order for one religion to be totally true, all other religions must be completely false? Explain.',
  'Do you think that ultimately, no matter what we believe about God, we will all end up at the same place as long as we are sincere? Explain your answer.',
  'If the world contained no religion, how might things be different?',
  'How do you react to a religious person who attempts to proselytize you?',
  'How do you define a cult?',
  'Can anyone know for sure that his or her religion is right? Explain.',
  'What is your definition of a miracle?',
  'If a bona fide miracle were to occur in your life, do you think that would convince you that some kind of intelligent Supreme Being exists? Why or why not?',
  'Why do you think most people find it difficult, if not impossible, to believe in miracles?',
  'Do you think angels and demons exist? Why or why not?',
  'What do you think angels are like, and what is their function here on earth?',
  'Do you believe you have a guardian angel?',
  'What is the greatest commandment?',
  'What is the greatest sin?',
  'Why do some people become uncomfortable discussing spiritual matters?',
  'What factors have most influenced your current beliefs about God?',
  'What does God want from us?',
  'If you could ask God to do any three things for you, and you knew he would do them, what would you ask him to do?',
  'When and how often do you pray? What motivates you to pray.',
  'On a scale from one to ten, how close to God do you feel? Explain.',
  'Rate the level of intensity you have about wanting to know God? Explain your answer.',
  'If a dimmer switch could represent your understanding of Christianity, how bright would your light be?',
  'Has there ever been a time you were convinced you received direction from God? Describe it.',
  'How do you discern God’s direction for your life?',
  'How has your belief or disbelief in God affected your life?',
  'What fears do you have about God?',
  'What makes it difficult for you to trust God?',
  'If you were to explain to a friend what it means to know God personally, what would you say?',
  'With everything in this universe that could consume God’s time and energy, how much do you think God really cares about what happens in your life?',
  'What is your greatest fear about what you’d be like if God were leading your life?',
  'Why doesn’t God do something about evil and suffering?',
  'When have you experienced a situation in which you believe God intervened? Describe it.',
  'What is your reaction to the Bible’s claim that Jesus is the only way to God?',
  'What has been your biggest obstacle to spiritual growth?',
  'Where are you in your spiritual journey?',
  'Using the compartments of a car, how would you describe where God fits into your life (trunk, driver’s seat, back seat, glove compartment, passenger seat, etc.)? Explain your answer.',
  'What prevents you from taking steps on your spiritual journey now?',
  'Who will be in heaven? Why?',
  'If God were to step in and wipe out every trace of evil, what would that do to the human population? Where would that leave you?',
  'When have you seen “hell” here on earth?',
  'Why do you suppose God doesn’t just eliminate Satan now?',
  'Where was God when terrorists attacked the World Trade Center and the Pentagon?',
  'If you were to die today, would you go to heaven? On what do you base your answer?',
  'If you could prove beyond a reasonable doubt that God exists, do you think you would seek out a relationship with him?',
  'If you believed in the God of the Bible, do you think it would impact the way you lived? Why or why not?',
  'Have you ever had something you would call a “spiritual experience”? Describe the situation.',
  'What religious issues are you struggling with these days?',
  'What kinds of things do you pray about most frequently?',
  'What personal religious experiences have had the most profound impact on you?',
  'How certain are you that your current belief about God is correct? What would change that?',
  'What do you think is the difference between a religious person who makes it into heaven and one who does not?',
  'Do you think it is possible for a man to gain the whole world and yet lose his soul? Explain.',
  'What does it mean to be made in the “image of God”?',
  'What would you suggest would be the best way for God to show his love?',
  'What’s your favorite Bible verse and why?',
  'What’s the most reassuring Bible promise you know? Explain your answer.',
  'Was there ever a time when you sincerely wanted to know God’s will regarding a decision you needed to make? What was the outcome? Describe the situation.',
  'What season are you currently in with regard to your spiritual life?',
  'What surprises you most about Jesus Christ?',
  'According to your understanding, how would you summarize the central message of Christianity?',
  'What’s something most of your friends don’t know about your spiritual side?',
  'What do you think God would say to you right now?',
  'What do you think God will say to you when you die?',
  'Why do you think Jesus was born? Why were you born?',
  'What’s one thing about the existence (or nonexistence) of God that scares you?',
  'The Bible says, “God is love.” What does that mean to you?',
  'Who is Jesus Christ to you?',
  'What’s the first question you will have for God when you die?',
  'Who’s the closest thing to a spiritual mentor to you?',
  'How has God demonstrated his love to you?',
  'What has produced the greatest spiritual growth in your life?',
  'Have you ever prayed a prayer of desperation? Describe the situation.',
  'How have you been disillusioned by religion?',
  'How comfortable are you discussing spiritual things with others?',
  'How is it possible that the death of one (Jesus Christ) overcomes (forgives) the sins of many (the whole human race)?',
  'Do you think it is possible to have a false sense of security about your eternal destiny? Explain.',
  'What do you think it means to be “born again”? What’s your knee-jerk reaction to this term?',
  'Is there something spiritual missing in your life? Explain.',
  'Do you agree with this statement: “Going to church doesn’t make you a Christian any more than going to a garage makes you an automobile” (Billy Sunday)? Why or why not?',
  'How would you define sin?',
  'What are the repercussions of sin, if any?',
  'Do you think it is possible to be indifferent or neutral toward God without offending him?',
  'What is your biggest personal spiritual dilemma or challenge?',
  'What do you think was the purpose of Jesus Christ’s death?',
  'What reasons do you think Christianity gives for its assertion that Jesus is the only way to God?',
  'In what ways is the Christian life difficult or impossible to live?',
  'How has God changed you?',
  'What do you think God’s attitude is toward you?',
  'Do you think becoming a Christian is an ongoing process, something that happens at a specific point in time, or a combination of the two? Give reasons for your answer.',
  'Why should God let you into heaven?',
  'Do you think God has ever used pain and suffering to get your attention? If so, what was he trying to get across to you?',
  'How confident are you about what will happen to you in the afterlife? Explain.',
  'Do you have any fears about being wrong about your spiritual beliefs? Explain.',
  'If you were face-to-face with Jesus, what would he say to you? Give a reason for your answer.',
  'Can hell, God’s justice, and God’s love all be real at the same time? Explain your answer.',
  'How comfortable would you feel about praying out loud with someone? Why?',
  'How do you distinguish God’s voice from your own thoughts?',
  'What miracle do you wish God would perform right now?',
  'What’s one doubt you have regarding the existence of a Supreme Being?',
  'What would Jesus do if he were in your shoes?',
  'When have you experienced the closest thing to a miracle? Describe it.',
  'If you were to identify someone as a Christian, what definitive factors would you look for to support that claim?',
  'Have you ever meditated for spiritual purposes? If so, describe your experience.',
  'Have you ever been baptized? What does the sacrament of baptism mean to you?',
  'How do you “feed your spirit”?',
  'What’s the closest you’ve come to having an encounter with God? Describe it.',
  'To what extent is your view of God influenced by your view of your father?',
  'For what are you most thankful to God?',
  'In your opinion, is the Christian message mostly “good news” or mostly “bad news”? Explain your response.',
  'When was a prayer of yours answered? Tell about it.',
  'How frequently, if ever, do you read the Bible? What motivates you to read the Bible?',
  'What’s one thing about God you don’t understand?',
  'Do you make comparisons with others on a spiritual level? Why or why not?',
  'How would you describe your own moral condition?',
  'Do you believe sin causes a gap between God and you? Why or why not?',
  'Do you ever become angry with God when things go wrong? Why or why not?',
  'Do you find it easy to ignore or avoid facing up to deep spiritual matters? Why or why not?',
  'In what ways do your religious beliefs impact the way you live your life?',
  'If you could ask God one question you knew he would answer right away, what would it be?'];
